server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zfcloudpandb
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      password:
      database: 0
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

app:
  default-role-id: 0
#knife4j:
#  enable: true
#  documents:
#    -
#      group: 2.X版本
#      name: 接口签名
#      locations: classpath:sign/*
#  setting:
#    language: zh-CN
#    enable-swagger-models: true
#    enable-document-manage: true
#    swagger-model-name: 实体类列表
#    enable-version: false
#    enable-reload-cache-parameter: false
#    enable-after-script: true
#    enable-filter-multipart-api-method-type: POST
#    enable-filter-multipart-apis: false
#    enable-request-cache: true
#    enable-host: false
#    enable-host-text: 192.168.0.193:8000
#    enable-home-custom: true
#    home-custom-path: classpath:markdown/home.md
#    enable-search: false
#    enable-footer: false
#    enable-footer-custom: true
#    footer-custom-content: Apache License 2.0 | Copyright  2019-[浙江八一菜刀股份有限公司](https://gitee.com/xiaoym/knife4j)
#    enable-dynamic-parameter: false
#    enable-debug: true
#    enable-open-api: false
#    enable-group: true
#  cors: false
#  production: false
#  basic:
#    enable: false
#    username: test
#    password: 12313